version: '3.1'
services:
  client:
    image: ethereum/client-go:latest
    entrypoint:
      - geth
      - --nousb
      - --nodiscover
      - --syncmode=light
      - --rpc
      - --rpcapi=les,eth,admin,web3
      - --rpcport=9444
      - --rpcaddr=0.0.0.0
      - --networkid=$NETWORKID
    ports:
      - "9444-9500:9444-9500"
    environment:
      - NETWORKID
