version: '3.4'

x-client: &client
 image: ethereum/client-go:latest
 entrypoint:
   - geth
   - --nousb
   - --nodiscover
   - --syncmode=light
   - --rpc
   - --rpcapi=les,eth,admin,web3
   - --rpcport=9444
   - --rpcaddr=0.0.0.0
   - --rpcvhosts=*
   - --networkid=$NETWORKID
 environment:
   - NETWORKID
 expose:
   - 9444
 networks:
   - light_network

services:
  client_1:
    <<: *client
    container_name: client_1
  client_2:
    <<: *client
    container_name: client_2

  spam:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - light_network

networks:
  light_network:
    driver: overlay
